version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      # 3000 is app port
      - '3000:3000' 
  
  mysql:
    image: docker.io/library/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: empleado
    ports:
      # 8000 is database port
      - '8000:3306'
    volumes:
      # Data saved in route C:\ProgrmaData\Mysql\MySQl_Container\Data
      - /c/ProgramData/MySQL/MySQL_Container/Data:/var/lib/mysql 
  
  phpmyadmin:
    image: docker.io/library/phpmyadmin:5.2.1
    environment:
      PMA_HOST: mysql 
      PMA_PORT: 8000
    ports:
      - '8081:80'