version: '3'

services:
  app:
    build: ./
    ports:
      # 3000 is app port
      - '3000:3000' 
    networks:
      - employees_net
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: empleado
    ports:
      # 8000 is database port
      - '8090:3306'
    networks:
      - employees_net
  
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql 
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8091:80'
    networks:
      - employees_net

networks:
  employees_net:
    driver: bridge